version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: finances-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finances
    ports:
      - "6000:5432"
